### ISSUE TITLE
Some site issue with `http://civl.cis.udel.edu`

### ISSUE THREAD

**Issue by chenrui333** [civl-verifier/civl-dev#2]
Looks like homepage got shifted from `https://vsl.cis.udel.edu/civl/` to `https://civl-verifier.github.io/`, but it looks like the artifact did not get moved to anywhere (this is the old artifact, `https://vsl.cis.udel.edu/lib/sw/civl/1.22/r5854/release/CIVL-1.22_5854.tgz`).

Any pointer of how to check the latest resource?

Thanks.

relates to https://github.com/Homebrew/homebrew-core/pull/195585

**Comment by bkragl** [comment]
The Civl verifier here is an entirely different project, not related to the project at the University of Delaware.
